drones:
  D-01:
    type: crazyflie
    uri: radio://0/80/2M/E7E7E7E715
    deck:
      flow: true
    default_height: 0.3
    default_velocity: 0.2   
    verified:
      radio: true
      usb: true
      python_connect: true
      battery_log: true
      motor_test_no_props: true
      flow_takeoff: true
